// swift-tools-version:5.9
// The swift-tools-version declares the minimum version of Swift required to build this package.
//
// Auto-generated by swift-openapi-bootstrapper
// Generated at: 2026-10-03T16:16:27.518737

import PackageDescription

let package = Package(
    name: "SonioxAPI",
    platforms: [
        .macOS(.v13),
        .iOS(.v16),
        .tvOS(.v16),
        .watchOS(.v9),
    ],
    products: [
        .library(
            name: "SonioxAPITypes",
            targets: ["SonioxAPITypes"]
        ),
        .library(
            name: "SonioxAPI",
            targets: ["SonioxAPI"]
        ),
    ],
    dependencies: [
        .package(url: "https://github.com/apple/swift-openapi-generator.git", from: "1.13.0"),
        .package(url: "https://github.com/apple/swift-openapi-runtime.git", from: "1.12.0"),
        .package(url: "https://github.com/swift-server/swift-openapi-async-http-client", from: "1.5.0"),
        .package(url: "https://github.com/atacan/UsefulThings", branch: "main"),
    ],
    targets: [
        // Types target: Contains generated types from OpenAPI spec
        .target(
            name: "SonioxAPITypes",
            dependencies: [
                .product(name: "OpenAPIRuntime", package: "swift-openapi-runtime")
            ]
        ),
        // Client target: Contains generated client and custom code
        .target(
            name: "SonioxAPI",
            dependencies: [
                .product(name: "OpenAPIRuntime", package: "swift-openapi-runtime"),
                .product(name: "OpenAPIAsyncHTTPClient", package: "swift-openapi-async-http-client"),
                .target(name: "SonioxAPITypes"),
            ]
        ),
        // Tests
        .testTarget(
            name: "SonioxAPITests",
            dependencies: [
                .target(name: "SonioxAPI"),
                .product(name: "UsefulThings", package: "UsefulThings"),
            ]
        ),
    ]
)
