// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) public import OpenAPIRuntime
#if os(Linux)
@preconcurrency public import struct Foundation.URL
@preconcurrency public import struct Foundation.Data
@preconcurrency public import struct Foundation.Date
#else
public import struct Foundation.URL
public import struct Foundation.Data
public import struct Foundation.Date
#endif
/// A type that performs HTTP operations defined by the OpenAPI document.
public protocol APIProtocol: Sendable {
    /// Get files
    ///
    /// Retrieves list of uploaded files.
    ///
    /// - Remark: HTTP `GET /v1/files`.
    /// - Remark: Generated from `#/paths//v1/files/get(get_files)`.
    func get_files(_ input: Operations.get_files.Input) async throws -> Operations.get_files.Output
    /// Upload file
    ///
    /// Uploads a new file.
    ///
    /// - Remark: HTTP `POST /v1/files`.
    /// - Remark: Generated from `#/paths//v1/files/post(upload_file)`.
    func upload_file(_ input: Operations.upload_file.Input) async throws -> Operations.upload_file.Output
    /// Get files count
    ///
    /// Returns the total number of files, split by source.
    ///
    /// - Remark: HTTP `GET /v1/files/count`.
    /// - Remark: Generated from `#/paths//v1/files/count/get(get_files_count)`.
    func get_files_count(_ input: Operations.get_files_count.Input) async throws -> Operations.get_files_count.Output
    /// Get file
    ///
    /// Retrieve metadata for an uploaded file.
    ///
    /// - Remark: HTTP `GET /v1/files/{file_id}`.
    /// - Remark: Generated from `#/paths//v1/files/{file_id}/get(get_file)`.
    func get_file(_ input: Operations.get_file.Input) async throws -> Operations.get_file.Output
    /// Delete file
    ///
    /// Permanently deletes specified file. If a transcription that has not started processing yet still references the file, that transcription fails with `file_not_found`, so delete the file only after the transcription reaches `completed` or `error`.
    ///
    /// - Remark: HTTP `DELETE /v1/files/{file_id}`.
    /// - Remark: Generated from `#/paths//v1/files/{file_id}/delete(delete_file)`.
    func delete_file(_ input: Operations.delete_file.Input) async throws -> Operations.delete_file.Output
    /// Get transcriptions
    ///
    /// Retrieves list of transcriptions.
    ///
    /// - Remark: HTTP `GET /v1/transcriptions`.
    /// - Remark: Generated from `#/paths//v1/transcriptions/get(get_transcriptions)`.
    func get_transcriptions(_ input: Operations.get_transcriptions.Input) async throws -> Operations.get_transcriptions.Output
    /// Create transcription
    ///
    /// Creates a new transcription.
    ///
    /// - Remark: HTTP `POST /v1/transcriptions`.
    /// - Remark: Generated from `#/paths//v1/transcriptions/post(create_transcription)`.
    func create_transcription(_ input: Operations.create_transcription.Input) async throws -> Operations.create_transcription.Output
    /// Get transcriptions count
    ///
    /// Returns the total number of transcriptions, split by request scope.
    ///
    /// - Remark: HTTP `GET /v1/transcriptions/count`.
    /// - Remark: Generated from `#/paths//v1/transcriptions/count/get(get_transcriptions_count)`.
    func get_transcriptions_count(_ input: Operations.get_transcriptions_count.Input) async throws -> Operations.get_transcriptions_count.Output
    /// Get transcription
    ///
    /// Retrieves detailed information about a specific transcription.
    ///
    /// - Remark: HTTP `GET /v1/transcriptions/{transcription_id}`.
    /// - Remark: Generated from `#/paths//v1/transcriptions/{transcription_id}/get(get_transcription)`.
    func get_transcription(_ input: Operations.get_transcription.Input) async throws -> Operations.get_transcription.Output
    /// Delete transcription
    ///
    /// Permanently deletes a transcription. Files uploaded through the Files API are not deleted; use the delete file endpoint to remove them. Cannot delete transcriptions that are currently processing.
    ///
    /// - Remark: HTTP `DELETE /v1/transcriptions/{transcription_id}`.
    /// - Remark: Generated from `#/paths//v1/transcriptions/{transcription_id}/delete(delete_transcription)`.
    func delete_transcription(_ input: Operations.delete_transcription.Input) async throws -> Operations.delete_transcription.Output
    /// Get transcription transcript
    ///
    /// Retrieves the full transcript text and detailed tokens for a completed transcription. Only available for successfully completed transcriptions.
    ///
    /// - Remark: HTTP `GET /v1/transcriptions/{transcription_id}/transcript`.
    /// - Remark: Generated from `#/paths//v1/transcriptions/{transcription_id}/transcript/get(get_transcription_transcript)`.
    func get_transcription_transcript(_ input: Operations.get_transcription_transcript.Input) async throws -> Operations.get_transcription_transcript.Output
    /// Get voices
    ///
    /// Retrieves the list of voices in your project.
    ///
    /// - Remark: HTTP `GET /v1/voices`.
    /// - Remark: Generated from `#/paths//v1/voices/get(get_voices)`.
    func get_voices(_ input: Operations.get_voices.Input) async throws -> Operations.get_voices.Output
    /// Create voice
    ///
    /// Uploads a reference audio clip and creates a new voice.
    ///
    /// - Remark: HTTP `POST /v1/voices`.
    /// - Remark: Generated from `#/paths//v1/voices/post(create_voice)`.
    func create_voice(_ input: Operations.create_voice.Input) async throws -> Operations.create_voice.Output
    /// Get voices count
    ///
    /// Returns the total number of voices in your project.
    ///
    /// - Remark: HTTP `GET /v1/voices/count`.
    /// - Remark: Generated from `#/paths//v1/voices/count/get(get_voices_count)`.
    func get_voices_count(_ input: Operations.get_voices_count.Input) async throws -> Operations.get_voices_count.Output
    /// Get voice
    ///
    /// Retrieve metadata for a voice.
    ///
    /// - Remark: HTTP `GET /v1/voices/{voice_id}`.
    /// - Remark: Generated from `#/paths//v1/voices/{voice_id}/get(get_voice)`.
    func get_voice(_ input: Operations.get_voice.Input) async throws -> Operations.get_voice.Output
    /// Delete voice
    ///
    /// Permanently deletes the specified voice and its embeddings.
    ///
    /// - Remark: HTTP `DELETE /v1/voices/{voice_id}`.
    /// - Remark: Generated from `#/paths//v1/voices/{voice_id}/delete(delete_voice)`.
    func delete_voice(_ input: Operations.delete_voice.Input) async throws -> Operations.delete_voice.Output
    /// Recompute voice
    ///
    /// Prepares the voice for use with available models it is not ready for yet. Use this after a new model is released to make an existing voice usable with it. Models the voice is already prepared for are left unchanged.
    ///
    /// - Remark: HTTP `POST /v1/voices/{voice_id}/recompute`.
    /// - Remark: Generated from `#/paths//v1/voices/{voice_id}/recompute/post(recompute_voice)`.
    func recompute_voice(_ input: Operations.recompute_voice.Input) async throws -> Operations.recompute_voice.Output
    /// Get models
    ///
    /// Retrieves list of available models and their attributes.
    ///
    /// - Remark: HTTP `GET /v1/models`.
    /// - Remark: Generated from `#/paths//v1/models/get(get_models)`.
    func get_models(_ input: Operations.get_models.Input) async throws -> Operations.get_models.Output
    /// Get TTS models
    ///
    /// Retrieves list of available TTS models and their attributes.
    ///
    /// - Remark: HTTP `GET /v1/tts-models`.
    /// - Remark: Generated from `#/paths//v1/tts-models/get(get_tts_models)`.
    func get_tts_models(_ input: Operations.get_tts_models.Input) async throws -> Operations.get_tts_models.Output
    /// Get shared voices
    ///
    /// Retrieves the shared voices built into a TTS model, optionally filtered by gender, age, accent, use case and style. All given filters must match. For the voices you have cloned yourself, see `GET /v1/voices` instead.
    ///
    /// - Remark: HTTP `GET /v1/shared-voices`.
    /// - Remark: Generated from `#/paths//v1/shared-voices/get(get_shared_voices)`.
    func get_shared_voices(_ input: Operations.get_shared_voices.Input) async throws -> Operations.get_shared_voices.Output
    /// Generate speech
    ///
    /// Generates audio from text using the TTS REST endpoint.
    ///
    /// - Remark: HTTP `POST /tts`.
    /// - Remark: Generated from `#/paths//tts/post(generate_tts)`.
    func generate_tts(_ input: Operations.generate_tts.Input) async throws -> Operations.generate_tts.Output
    /// Create temporary API key
    ///
    /// Creates a short-lived API key for specific temporary use cases. The key will automatically expire after the specified duration.
    ///
    /// Use `single_use` and `max_session_duration_seconds` to limit how the key can be used by a client. See the [Temporary API keys guide](https://soniox.com/docs/guides/temporary-api-keys) for details.
    ///
    ///
    /// - Remark: HTTP `POST /v1/auth/temporary-api-key`.
    /// - Remark: Generated from `#/paths//v1/auth/temporary-api-key/post(create_temporary_api_key)`.
    func create_temporary_api_key(_ input: Operations.create_temporary_api_key.Input) async throws -> Operations.create_temporary_api_key.Output
    /// Get usage logs
    ///
    /// Returns per-request usage log entries for the project. The project is implied by the API key used for authentication. Filters by request end time. The window between start_time and end_time must not exceed 31 days. start_time must not be earlier than 91 days ago.
    ///
    /// - Remark: HTTP `GET /v1/usage-logs`.
    /// - Remark: Generated from `#/paths//v1/usage-logs/get(get_usage_logs)`.
    func get_usage_logs(_ input: Operations.get_usage_logs.Input) async throws -> Operations.get_usage_logs.Output
    /// Get usage summary
    ///
    /// Returns daily cost and activity for the project, broken down per model and summed across all models. The project is implied by the API key used for authentication.
    ///
    /// Usage is aggregated by whole UTC day. The window is half-open, `[start_time, end_time)`, and a day is included when the window covers any part of it, so an `end_time` exactly at midnight excludes that day. The window must not cover more than 366 UTC days.
    ///
    ///
    /// - Remark: HTTP `GET /v1/usage/summary`.
    /// - Remark: Generated from `#/paths//v1/usage/summary/get(get_usage_summary)`.
    func get_usage_summary(_ input: Operations.get_usage_summary.Input) async throws -> Operations.get_usage_summary.Output
    /// Get concurrency limits
    ///
    /// Current concurrent counts plus configured concurrency limits for the project and its organization. Region-scoped.
    ///
    /// - Remark: HTTP `GET /v1/concurrency-limits`.
    /// - Remark: Generated from `#/paths//v1/concurrency-limits/get(get_concurrency_limits)`.
    func get_concurrency_limits(_ input: Operations.get_concurrency_limits.Input) async throws -> Operations.get_concurrency_limits.Output
    /// Get concurrent streams history
    ///
    /// Returns historical concurrent stream counts for the project, aggregated per period. The project is implied by the API key used for authentication. Region-scoped.
    ///
    /// Every aggregation period in the requested window is returned, with no gaps. Periods with no recorded activity have every field set to `0`.
    ///
    ///
    /// - Remark: HTTP `GET /v1/concurrent-streams-history`.
    /// - Remark: Generated from `#/paths//v1/concurrent-streams-history/get(get_concurrent_streams_history)`.
    func get_concurrent_streams_history(_ input: Operations.get_concurrent_streams_history.Input) async throws -> Operations.get_concurrent_streams_history.Output
}

/// Convenience overloads for operation inputs.
extension APIProtocol {
    /// Get files
    ///
    /// Retrieves list of uploaded files.
    ///
    /// - Remark: HTTP `GET /v1/files`.
    /// - Remark: Generated from `#/paths//v1/files/get(get_files)`.
    public func get_files(
        query: Operations.get_files.Input.Query = .init(),
        headers: Operations.get_files.Input.Headers = .init()
    ) async throws -> Operations.get_files.Output {
        try await get_files(Operations.get_files.Input(
            query: query,
            headers: headers
        ))
    }
    /// Upload file
    ///
    /// Uploads a new file.
    ///
    /// - Remark: HTTP `POST /v1/files`.
    /// - Remark: Generated from `#/paths//v1/files/post(upload_file)`.
    public func upload_file(
        headers: Operations.upload_file.Input.Headers = .init(),
        body: Operations.upload_file.Input.Body
    ) async throws -> Operations.upload_file.Output {
        try await upload_file(Operations.upload_file.Input(
            headers: headers,
            body: body
        ))
    }
    /// Get files count
    ///
    /// Returns the total number of files, split by source.
    ///
    /// - Remark: HTTP `GET /v1/files/count`.
    /// - Remark: Generated from `#/paths//v1/files/count/get(get_files_count)`.
    public func get_files_count(headers: Operations.get_files_count.Input.Headers = .init()) async throws -> Operations.get_files_count.Output {
        try await get_files_count(Operations.get_files_count.Input(headers: headers))
    }
    /// Get file
    ///
    /// Retrieve metadata for an uploaded file.
    ///
    /// - Remark: HTTP `GET /v1/files/{file_id}`.
    /// - Remark: Generated from `#/paths//v1/files/{file_id}/get(get_file)`.
    public func get_file(
        path: Operations.get_file.Input.Path,
        headers: Operations.get_file.Input.Headers = .init()
    ) async throws -> Operations.get_file.Output {
        try await get_file(Operations.get_file.Input(
            path: path,
            headers: headers
        ))
    }
    /// Delete file
    ///
    /// Permanently deletes specified file. If a transcription that has not started processing yet still references the file, that transcription fails with `file_not_found`, so delete the file only after the transcription reaches `completed` or `error`.
    ///
    /// - Remark: HTTP `DELETE /v1/files/{file_id}`.
    /// - Remark: Generated from `#/paths//v1/files/{file_id}/delete(delete_file)`.
    public func delete_file(
        path: Operations.delete_file.Input.Path,
        headers: Operations.delete_file.Input.Headers = .init()
    ) async throws -> Operations.delete_file.Output {
        try await delete_file(Operations.delete_file.Input(
            path: path,
            headers: headers
        ))
    }
    /// Get transcriptions
    ///
    /// Retrieves list of transcriptions.
    ///
    /// - Remark: HTTP `GET /v1/transcriptions`.
    /// - Remark: Generated from `#/paths//v1/transcriptions/get(get_transcriptions)`.
    public func get_transcriptions(
        query: Operations.get_transcriptions.Input.Query = .init(),
        headers: Operations.get_transcriptions.Input.Headers = .init()
    ) async throws -> Operations.get_transcriptions.Output {
        try await get_transcriptions(Operations.get_transcriptions.Input(
            query: query,
            headers: headers
        ))
    }
    /// Create transcription
    ///
    /// Creates a new transcription.
    ///
    /// - Remark: HTTP `POST /v1/transcriptions`.
    /// - Remark: Generated from `#/paths//v1/transcriptions/post(create_transcription)`.
    public func create_transcription(
        headers: Operations.create_transcription.Input.Headers = .init(),
        body: Operations.create_transcription.Input.Body
    ) async throws -> Operations.create_transcription.Output {
        try await create_transcription(Operations.create_transcription.Input(
            headers: headers,
            body: body
        ))
    }
    /// Get transcriptions count
    ///
    /// Returns the total number of transcriptions, split by request scope.
    ///
    /// - Remark: HTTP `GET /v1/transcriptions/count`.
    /// - Remark: Generated from `#/paths//v1/transcriptions/count/get(get_transcriptions_count)`.
    public func get_transcriptions_count(headers: Operations.get_transcriptions_count.Input.Headers = .init()) async throws -> Operations.get_transcriptions_count.Output {
        try await get_transcriptions_count(Operations.get_transcriptions_count.Input(headers: headers))
    }
    /// Get transcription
    ///
    /// Retrieves detailed information about a specific transcription.
    ///
    /// - Remark: HTTP `GET /v1/transcriptions/{transcription_id}`.
    /// - Remark: Generated from `#/paths//v1/transcriptions/{transcription_id}/get(get_transcription)`.
    public func get_transcription(
        path: Operations.get_transcription.Input.Path,
        headers: Operations.get_transcription.Input.Headers = .init()
    ) async throws -> Operations.get_transcription.Output {
        try await get_transcription(Operations.get_transcription.Input(
            path: path,
            headers: headers
        ))
    }
    /// Delete transcription
    ///
    /// Permanently deletes a transcription. Files uploaded through the Files API are not deleted; use the delete file endpoint to remove them. Cannot delete transcriptions that are currently processing.
    ///
    /// - Remark: HTTP `DELETE /v1/transcriptions/{transcription_id}`.
    /// - Remark: Generated from `#/paths//v1/transcriptions/{transcription_id}/delete(delete_transcription)`.
    public func delete_transcription(
        path: Operations.delete_transcription.Input.Path,
        headers: Operations.delete_transcription.Input.Headers = .init()
    ) async throws -> Operations.delete_transcription.Output {
        try await delete_transcription(Operations.delete_transcription.Input(
            path: path,
            headers: headers
        ))
    }
    /// Get transcription transcript
    ///
    /// Retrieves the full transcript text and detailed tokens for a completed transcription. Only available for successfully completed transcriptions.
    ///
    /// - Remark: HTTP `GET /v1/transcriptions/{transcription_id}/transcript`.
    /// - Remark: Generated from `#/paths//v1/transcriptions/{transcription_id}/transcript/get(get_transcription_transcript)`.
    public func get_transcription_transcript(
        path: Operations.get_transcription_transcript.Input.Path,
        headers: Operations.get_transcription_transcript.Input.Headers = .init()
    ) async throws -> Operations.get_transcription_transcript.Output {
        try await get_transcription_transcript(Operations.get_transcription_transcript.Input(
            path: path,
            headers: headers
        ))
    }
    /// Get voices
    ///
    /// Retrieves the list of voices in your project.
    ///
    /// - Remark: HTTP `GET /v1/voices`.
    /// - Remark: Generated from `#/paths//v1/voices/get(get_voices)`.
    public func get_voices(
        query: Operations.get_voices.Input.Query = .init(),
        headers: Operations.get_voices.Input.Headers = .init()
    ) async throws -> Operations.get_voices.Output {
        try await get_voices(Operations.get_voices.Input(
            query: query,
            headers: headers
        ))
    }
    /// Create voice
    ///
    /// Uploads a reference audio clip and creates a new voice.
    ///
    /// - Remark: HTTP `POST /v1/voices`.
    /// - Remark: Generated from `#/paths//v1/voices/post(create_voice)`.
    public func create_voice(
        headers: Operations.create_voice.Input.Headers = .init(),
        body: Operations.create_voice.Input.Body
    ) async throws -> Operations.create_voice.Output {
        try await create_voice(Operations.create_voice.Input(
            headers: headers,
            body: body
        ))
    }
    /// Get voices count
    ///
    /// Returns the total number of voices in your project.
    ///
    /// - Remark: HTTP `GET /v1/voices/count`.
    /// - Remark: Generated from `#/paths//v1/voices/count/get(get_voices_count)`.
    public func get_voices_count(headers: Operations.get_voices_count.Input.Headers = .init()) async throws -> Operations.get_voices_count.Output {
        try await get_voices_count(Operations.get_voices_count.Input(headers: headers))
    }
    /// Get voice
    ///
    /// Retrieve metadata for a voice.
    ///
    /// - Remark: HTTP `GET /v1/voices/{voice_id}`.
    /// - Remark: Generated from `#/paths//v1/voices/{voice_id}/get(get_voice)`.
    public func get_voice(
        path: Operations.get_voice.Input.Path,
        headers: Operations.get_voice.Input.Headers = .init()
    ) async throws -> Operations.get_voice.Output {
        try await get_voice(Operations.get_voice.Input(
            path: path,
            headers: headers
        ))
    }
    /// Delete voice
    ///
    /// Permanently deletes the specified voice and its embeddings.
    ///
    /// - Remark: HTTP `DELETE /v1/voices/{voice_id}`.
    /// - Remark: Generated from `#/paths//v1/voices/{voice_id}/delete(delete_voice)`.
    public func delete_voice(
        path: Operations.delete_voice.Input.Path,
        headers: Operations.delete_voice.Input.Headers = .init()
    ) async throws -> Operations.delete_voice.Output {
        try await delete_voice(Operations.delete_voice.Input(
            path: path,
            headers: headers
        ))
    }
    /// Recompute voice
    ///
    /// Prepares the voice for use with available models it is not ready for yet. Use this after a new model is released to make an existing voice usable with it. Models the voice is already prepared for are left unchanged.
    ///
    /// - Remark: HTTP `POST /v1/voices/{voice_id}/recompute`.
    /// - Remark: Generated from `#/paths//v1/voices/{voice_id}/recompute/post(recompute_voice)`.
    public func recompute_voice(
        path: Operations.recompute_voice.Input.Path,
        headers: Operations.recompute_voice.Input.Headers = .init(),
        body: Operations.recompute_voice.Input.Body
    ) async throws -> Operations.recompute_voice.Output {
        try await recompute_voice(Operations.recompute_voice.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// Get models
    ///
    /// Retrieves list of available models and their attributes.
    ///
    /// - Remark: HTTP `GET /v1/models`.
    /// - Remark: Generated from `#/paths//v1/models/get(get_models)`.
    public func get_models(headers: Operations.get_models.Input.Headers = .init()) async throws -> Operations.get_models.Output {
        try await get_models(Operations.get_models.Input(headers: headers))
    }
    /// Get TTS models
    ///
    /// Retrieves list of available TTS models and their attributes.
    ///
    /// - Remark: HTTP `GET /v1/tts-models`.
    /// - Remark: Generated from `#/paths//v1/tts-models/get(get_tts_models)`.
    public func get_tts_models(headers: Operations.get_tts_models.Input.Headers = .init()) async throws -> Operations.get_tts_models.Output {
        try await get_tts_models(Operations.get_tts_models.Input(headers: headers))
    }
    /// Get shared voices
    ///
    /// Retrieves the shared voices built into a TTS model, optionally filtered by gender, age, accent, use case and style. All given filters must match. For the voices you have cloned yourself, see `GET /v1/voices` instead.
    ///
    /// - Remark: HTTP `GET /v1/shared-voices`.
    /// - Remark: Generated from `#/paths//v1/shared-voices/get(get_shared_voices)`.
    public func get_shared_voices(
        query: Operations.get_shared_voices.Input.Query,
        headers: Operations.get_shared_voices.Input.Headers = .init()
    ) async throws -> Operations.get_shared_voices.Output {
        try await get_shared_voices(Operations.get_shared_voices.Input(
            query: query,
            headers: headers
        ))
    }
    /// Generate speech
    ///
    /// Generates audio from text using the TTS REST endpoint.
    ///
    /// - Remark: HTTP `POST /tts`.
    /// - Remark: Generated from `#/paths//tts/post(generate_tts)`.
    public func generate_tts(
        headers: Operations.generate_tts.Input.Headers = .init(),
        body: Operations.generate_tts.Input.Body
    ) async throws -> Operations.generate_tts.Output {
        try await generate_tts(Operations.generate_tts.Input(
            headers: headers,
            body: body
        ))
    }
    /// Create temporary API key
    ///
    /// Creates a short-lived API key for specific temporary use cases. The key will automatically expire after the specified duration.
    ///
    /// Use `single_use` and `max_session_duration_seconds` to limit how the key can be used by a client. See the [Temporary API keys guide](https://soniox.com/docs/guides/temporary-api-keys) for details.
    ///
    ///
    /// - Remark: HTTP `POST /v1/auth/temporary-api-key`.
    /// - Remark: Generated from `#/paths//v1/auth/temporary-api-key/post(create_temporary_api_key)`.
    public func create_temporary_api_key(
        headers: Operations.create_temporary_api_key.Input.Headers = .init(),
        body: Operations.create_temporary_api_key.Input.Body
    ) async throws -> Operations.create_temporary_api_key.Output {
        try await create_temporary_api_key(Operations.create_temporary_api_key.Input(
            headers: headers,
            body: body
        ))
    }
    /// Get usage logs
    ///
    /// Returns per-request usage log entries for the project. The project is implied by the API key used for authentication. Filters by request end time. The window between start_time and end_time must not exceed 31 days. start_time must not be earlier than 91 days ago.
    ///
    /// - Remark: HTTP `GET /v1/usage-logs`.
    /// - Remark: Generated from `#/paths//v1/usage-logs/get(get_usage_logs)`.
    public func get_usage_logs(
        query: Operations.get_usage_logs.Input.Query,
        headers: Operations.get_usage_logs.Input.Headers = .init()
    ) async throws -> Operations.get_usage_logs.Output {
        try await get_usage_logs(Operations.get_usage_logs.Input(
            query: query,
            headers: headers
        ))
    }
    /// Get usage summary
    ///
    /// Returns daily cost and activity for the project, broken down per model and summed across all models. The project is implied by the API key used for authentication.
    ///
    /// Usage is aggregated by whole UTC day. The window is half-open, `[start_time, end_time)`, and a day is included when the window covers any part of it, so an `end_time` exactly at midnight excludes that day. The window must not cover more than 366 UTC days.
    ///
    ///
    /// - Remark: HTTP `GET /v1/usage/summary`.
    /// - Remark: Generated from `#/paths//v1/usage/summary/get(get_usage_summary)`.
    public func get_usage_summary(
        query: Operations.get_usage_summary.Input.Query,
        headers: Operations.get_usage_summary.Input.Headers = .init()
    ) async throws -> Operations.get_usage_summary.Output {
        try await get_usage_summary(Operations.get_usage_summary.Input(
            query: query,
            headers: headers
        ))
    }
    /// Get concurrency limits
    ///
    /// Current concurrent counts plus configured concurrency limits for the project and its organization. Region-scoped.
    ///
    /// - Remark: HTTP `GET /v1/concurrency-limits`.
    /// - Remark: Generated from `#/paths//v1/concurrency-limits/get(get_concurrency_limits)`.
    public func get_concurrency_limits(headers: Operations.get_concurrency_limits.Input.Headers = .init()) async throws -> Operations.get_concurrency_limits.Output {
        try await get_concurrency_limits(Operations.get_concurrency_limits.Input(headers: headers))
    }
    /// Get concurrent streams history
    ///
    /// Returns historical concurrent stream counts for the project, aggregated per period. The project is implied by the API key used for authentication. Region-scoped.
    ///
    /// Every aggregation period in the requested window is returned, with no gaps. Periods with no recorded activity have every field set to `0`.
    ///
    ///
    /// - Remark: HTTP `GET /v1/concurrent-streams-history`.
    /// - Remark: Generated from `#/paths//v1/concurrent-streams-history/get(get_concurrent_streams_history)`.
    public func get_concurrent_streams_history(
        query: Operations.get_concurrent_streams_history.Input.Query,
        headers: Operations.get_concurrent_streams_history.Input.Headers = .init()
    ) async throws -> Operations.get_concurrent_streams_history.Output {
        try await get_concurrent_streams_history(Operations.get_concurrent_streams_history.Input(
            query: query,
            headers: headers
        ))
    }
}

/// Server URLs defined in the OpenAPI document.
public enum Servers {
    /// Soniox API
    public enum Server1 {
        /// Soniox API
        public static func url() throws -> Foundation.URL {
            try Foundation.URL(
                validatingOpenAPIServerURL: "https://api.soniox.com",
                variables: []
            )
        }
    }
    /// Soniox API
    @available(*, deprecated, renamed: "Servers.Server1.url")
    public static func server1() throws -> Foundation.URL {
        try Foundation.URL(
            validatingOpenAPIServerURL: "https://api.soniox.com",
            variables: []
        )
    }
}
